stages:
  - stage: Build
    displayName: 'Build Azure WebApp'
    jobs:
    - template: azure-pipelines-build-template.yml
  - stage: DeployDev
    condition: succeeded()
    dependsOn: Build
    variables:
    - group: 'webapp-dev-env-variable-group'
    jobs:
    - template: azure-pipelines-deployment-template.yml
      parameters:
        environment: 'Dev'
        webAppName: '$(WebAppName)'
        azureConnectionName: '$(AzureConnectionName)'
        subscriptionId: '$(SubscriptionId)'
        region: '$(Region)'
        resourceGroupName: '$(ResourceGroupName)'
  - stage: DeployTest
    condition: succeeded()
    dependsOn: DeployDev
    variables:
    - group: 'webapp-test-env-variable-group'
    jobs:
    - template: azure-pipelines-deployment-template.yml
      parameters:
        environment: 'Test'
        webAppName: '$(WebAppName)'
        azureConnectionName: '$(AzureConnectionName)'
        subscriptionId: '$(SubscriptionId)'
        region: '$(Region)'
        resourceGroupName: '$(ResourceGroupName)'
  - stage: DeployProd
    condition: succeeded()
    dependsOn: DeployTest
    variables:
    - group: 'webapp-prod-env-variable-group'
    jobs:
    - template: azure-pipelines-deployment-template.yml
      parameters:
        environment: 'Prod'
        webAppName: '$(WebAppName)'
        azureConnectionName: '$(AzureConnectionName)'
        subscriptionId: '$(SubscriptionId)'
        region: '$(Region)'
        resourceGroupName: '$(ResourceGroupName)'