parameters:
  environment: ''
  webAppName: ''
  azureConnectionName: ''
  subscriptionId: ''
  resourceGroupName: ''
  region: ''
jobs:
  - deployment: DeployWebApp
    displayName: "Deploy Azure environment"
    environment: ${{ parameters.environment }}
    pool:
      vmImage: 'Ubuntu-20.04'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Deploy infrastructure'
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'Microsoft Internal Subscription 1'
              subscriptionId: '${{ parameters.subscriptionId }}'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '${{ parameters.resourceGroupName }}'
              location: '${{ parameters.region }}'
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/Infrastructure/Infrastructure/azuredeploy.json'
              csmParametersFile: '$(Pipeline.Workspace)/Infrastructure/Infrastructure/azuredeploy.parameters.json'
              overrideParameters: -webAppName ${{ parameters.webAppName }}
              deploymentMode: 'Incremental'
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy webapp'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Microsoft Internal Subscription 1'
              WebAppKind: 'webAppLinux'
              WebAppName: '${{ parameters.webAppName }}'
              packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
              RuntimeStack: 'DOTNET|5.0'
