parameters:
- name: yesNo # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false
- name: environment
  type: string

jobs:
  - deployment: Deploy
    displayName: 'Deploy WebApp'
    environment: ${{ parameters.environment }}
    pool:
      vmImage: 'Ubuntu-20.04'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo ${{ parameters.yesNo }} ${{ parameters.environment }}