stages:
  - stage: Build
    variables:
    - group: 'webapp-dev-env-variable-group'
    jobs:
    - template: azure-pipelines-deployment-template.yml
      parameters:
        name: 'dev'
        webAppName: '$(WebAppName)'
        frameworkVersion: '5.0'
        toolVersion: '1.0'

    - template: azure-pipelines-deployment-template.yml
      parameters:
        name: 'staging'
        webAppName: '$(WebAppName)'
        frameworkVersion: '5.0'
        toolVersion: '1.0'

    - template: azure-pipelines-deployment-template.yml
      parameters:
        name: 'production'
        webAppName: '$(WebAppName)'
        frameworkVersion: '5.0'
        toolVersion: '1.0'
