parameters:
  environment: ''
  webAppName: ''
  frameworkVersion: ''
  toolVersion: ''

jobs:
- job: Build${{ parameters.environment }}

  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo This job will running on env ${{ parameters.environment }} with framework version ${{ parameters.frameworkVersion }} and tool ${{ parameters.toolVersion }} with the webapp name ${{ parameters.webAppName }}

    # All the tasks you need to build the project...
