parameters:
- name: yesNo # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false

jobs:
  - deployment: Deploy
    displayName: 'Deploy WebApp'
    environment: ${{ parameters.environment }}
    variables:
      - group: 'webapp-dev-env-variable-group'
    pool:
      vmImage: 'Ubuntu-20.04'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo ${{ parameters.yesNo }}

          - task: DownloadBuildArtifacts@0
            displayName: 'Download the build artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.DefaultWorkingDirectory)'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy to App Service'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(AzureConnectionName)'
              appType: 'webAppLinux'
              WebAppName: '${{ parameters.webAppName }}'
              packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
              RuntimeStack: 'DOTNET|5.0'