jobs:
  - deployment: Deploy
    displayName: 'Deploy WebApp'
    environment: ${{ parameters.environment }}
    variables:
      - group: 'webapp-dev-env-variable-group'
    pool:
      vmImage: 'Ubuntu-20.04'
    strategy:
      runOnce:
        deploy:
          steps:

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo This job will running on env ${{ parameters.environment }} and ${{ parameters.WebAppName }}

          - task: DownloadBuildArtifacts@0
            displayName: 'Download the build artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.DefaultWorkingDirectory)'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy to App Service'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(AzureConnectionName)'
              appType: 'webAppLinux'
              WebAppName: '${{ parameters.WebAppName }}'
              packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
              RuntimeStack: 'DOTNET|5.0'