jobs:
  - deployment: Deploy
    displayName: "Deploy RM Azure Functons"
    environment: $(environment)
    pool:
      vmImage: 'Ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download the build artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.DefaultWorkingDirectory)'

          - task: AzureWebApp@1
            displayName: Release package to Azure WebApp
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(appName)
              resourceGroupName: $(resourceGroupName)
              package: $(System.DefaultWorkingDirectory)/**/*.zip