parameters:
  environment: ''
  webAppName: ''
  azureConnectionName: ''
jobs:
  - deployment: Deploy
      displayName: "Deploy Azure WebApp"
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'Ubuntu-20.04'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadBuildArtifacts@0
              displayName: 'Download the build artifacts'
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(System.DefaultWorkingDirectory)'

            - task: AzureWebApp@1
              displayName: Release package to Azure WebApp
              inputs:
                azureSubscription: '${{ parameters.azureConnectionName }}'
                appType: webAppLinux
                appName: '${{ parameters.webAppName }}'
                resourceGroupName: 'helloworld-dev-rg'
                package: $(System.DefaultWorkingDirectory)/**/*.zip