jobs:
  - deployment: Deploy
    displayName: 'Deploy RM Azure Functons'
    environment: 'Dev'
    pool:
      vmImage: 'Ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download the build artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.DefaultWorkingDirectory)'

          - task: AzureWebApp@1
            displayName: Release package to Azure WebApp
            inputs:
              azureSubscription: 'Microsoft Internal Consumption 1'
              appType: webAppLinux
              appName: 'helloworld-dev-mimott'
              resourceGroupName: 'helloworld-dev-rg'
              package: $(System.DefaultWorkingDirectory)/**/*.zip