parameters:
  environment: ''
  webAppName: ''
  azureConnectionName: ''
jobs:
  - deployment: DeployWebApp
    displayName: "Deploy Azure WebApp"
    environment: ${{ parameters.environment }}
    pool:
      vmImage: 'Ubuntu-20.04'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download the build artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.DefaultWorkingDirectory)'
          - task: AzureRMWebAppDeployment@4
            displayName: Azure App Service Deploy
            inputs:
              ConnectionType: AzureRM
              appType: webAppLinux
              ConnectedServiceName: 'Microsoft Internal Consumption 1'
              WebAppName: '${{ parameters.webAppName }}'