parameters:
  environment: ''
  webAppName: ''
  azureConnectionName: ''
jobs:
  - deployment: DeployWebApp
    displayName: "Deploy Azure WebApp"
    environment: ${{ parameters.environment }}
    pool:
      vmImage: 'Ubuntu-20.04'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download the build artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.DefaultWorkingDirectory)'
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'Microsoft Internal Subscription 1'
              subscriptionId: '5648d12a-ba49-4789-8793-6f7cc54e1556'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'helloworld-dev-rg'
              location: 'France Central'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.ArtifactStagingDirectory)/Infrastructure/Infrastructure/azuredeploy.json'
              csmParametersFile: '$(Build.ArtifactStagingDirectory)/Infrastructure/Infrastructure/azuredeploy.parameters.json'
              overrideParameters: -webAppName helloworld-dev-mimott
              deploymentMode: 'Incremental'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Microsoft Internal Subscription 1'
              appType: 'webAppLinux'
              WebAppName: '${{ parameters.webAppName }}'
              packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'