parameters:
  environment: ''
  webAppName: ''
  azureConnectionName: ''
jobs:
  - deployment: DeployWebApp
    displayName: "Deploy Azure WebApp"
    environment: ${{ parameters.environment }}
    pool:
      vmImage: 'Ubuntu-20.04'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download the build artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.DefaultWorkingDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Microsoft Internal Subscription 1'
              appType: 'webAppLinux'
              WebAppName: '${{ parameters.webAppName }}'
              packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'