jobs:
  - deployment: Deploy
    displayName: 'Deploy WebApp'
    environment: $(environment)
    variables:
      - group: 'webapp-dev-env-variable-group'
    pool:
      vmImage: 'Ubuntu-20.04'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download the build artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.DefaultWorkingDirectory)'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy to App Service'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Microsoft Internal Subscription 1'
              appType: 'webAppLinux'
              WebAppName: 'helloworld-dev-mimott'
              packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
              RuntimeStack: 'DOTNET|5.0'

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                echo '$(AzureConnectionName)'