name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: Ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore WebApp
    - name: Build
      run: dotnet build WebApp --configuration Release --no-restore
    - name: Publish
      run: dotnet publish WebApp --configuration Release -o ./output/
    - name: Test
      run: dotnet test WebApp --no-restore --verbosity normal
    - name: Publish artifact
      uses: actions/upload-artifact@v1
      with:
        name: aspnet-webapp
        path: ./output/
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with: 
        app-name: demogithub-mcklmt
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: ./output/
